var GenreActions = {
    GENRE_PAGE_LOAD: 'GENRE_PAGE_LOAD',
    GENRE_PAGE_ADD: 'GENRE_PAGE_ADD',
    GENRE_PAGE_EDIT: 'GENRE_PAGE_EDIT',
    GENRE_PAGE_OPEN_EDIT_DIALOG: 'GENRE_PAGE_OPEN_EDIT_DIALOG',
    GENRE_PAGE_CLOSE_EDIT_DIALOG: 'GENRE_PAGE_CLOSE_EDIT_DIALOG'
};

export default GenreActions;